name: Build Barcodes Suite for macOS

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '**/*.py'
      - '.github/workflows/build-macos.yml'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-14
            label: AppleSilicon   # M1/M2/M3
          - os: macos-13
            label: Intel
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # 🔎 Find barcodes_suite.py anywhere in the repo and expose its folder as "dir"
      - name: Locate project file
        id: find
        shell: bash
        run: |
          set -e
          FILE="$(git ls-files | grep -E '(^|/)(barcodes_suite\.py)$' | head -n1 || true)"
          if [ -z "$FILE" ]; then
            echo "ERROR: barcodes_suite.py not found in repository." >&2
            exit 1
          fi
          DIR="$(dirname "$FILE")"
          echo "dir=$DIR" >> $GITHUB_OUTPUT
          echo "file=$FILE" >> $GITHUB_OUTPUT
          echo "Found at: $FILE"
          ls -la "$DIR"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller openpyxl

      - name: Build app
        working-directory: ${{ steps.find.outputs.dir }}
        run: |
          pyinstaller --noconfirm --windowed --name "Barcodes Suite" barcodes_suite.py
          cd dist
          zip -r "Barcodes_Suite_${{ matrix.label }}.zip" "Barcodes Suite.app"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Barcodes_Suite_${{ matrix.label }}
          path: ${{ steps.find.outputs.dir }}/dist/Barcodes_Suite_${{ matrix.label }}.zip
