name: Build Barcodes Suite for macOS

on:
  workflow_dispatch:
  push:
    paths:
      - "barcodes_suite.py"
      - "requirements.txt"
      - ".github/workflows/build-macos.yml"

jobs:
  build:
    name: Build (${{ matrix.arch_label }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: macos-13
            arch_label: Intel
          - runner: macos-14
            arch_label: AppleSilicon
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build app
        run: |
          pyinstaller --noconfirm --windowed --name "Barcodes Suite" barcodes_suite.py

      - name: Zip app
        run: |
          ditto -c -k --sequesterRsrc --keepParent "dist/Barcodes Suite.app" "Barcodes_Suite_${{ matrix.arch_label }}.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Barcodes Suite macOS ${{ matrix.arch_label }}
          path: Barcodes_Suite_${{ matrix.arch_label }}.zip
